### ISSUE TITLE
Add Bintray credentials to .travis.yml

### ISSUE THREAD

**Issue by BenFradet** [snowplow-incubator/scala-lru-map#2]
- BINTRAY_SNOWPLOW_MAVEN_USER
- BINTRAY_SNOWPLOW_MAVEN_API_KEY

Additionally, there is no scala-maxmind-iplookups repo in snowplow-maven so that needs to be created.
Also, mirroring to central will need to be enabled.

- [x] AD: add creds
- [x] AD: create repo in Bintray
- [x] ER: push first M1
- [x] AD: add to JCenter
- [x] AD: activate Maven Central sync

**Comment by alexanderdean** [comment]
Created https://bintray.com/snowplow/snowplow-maven/scala-lru-map

Renamed repo to add "snowplow-" at start.

**Comment by three** [comment]
@alexanderdean I get this error on deploy. Can you add the library to JCenter?

```
[error] (bintraySyncMavenCentral) failed to sync snowplow/lru-map@0.1.0-M1 with maven central: {"message":"In order to sync to Maven Central your package must be included in the JCenter repository"}
[error] Total time: 1 s, completed Jun 25, 2018 2:46:02 PM
```

**Comment by alexanderdean** [comment]
Done, also renamed Bintray package name to scala-lru-map

**Comment by BenFradet** [comment]
@alexanderdean can you enable maven central syncing? It was correctly mirrored to JCenter.

**Comment by alexanderdean** [comment]
I think the syncing happens automatically, but I could be wrong, and I've done a manual sync just to be sure.

**Comment by BenFradet** [comment]
@three can you do an M2 to check everything is in order?

**Comment by three** [comment]
@BenFradet Done, looks like everything's working now https://travis-ci.org/snowplow-incubator/scala-lru-map/jobs/397067984

**Comment by BenFradet** [comment]
Ok please integrate that M release with iplookups

**Comment by three** [comment]
@BenFradet I committed it to the encapsulate side effects PR

**Comment by BenFradet** [comment]
published, closing
